server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: attendance-backend
  
  main:
    allow-circular-references: true
    
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/attendance_db}
    username: ${DATABASE_USERNAME:attendance_user}
    password: ${DATABASE_PASSWORD:attendance_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    open-in-view: false
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      adjust-dates-to-context-time-zone: false
    time-zone: UTC

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.company.attendance: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific configuration
app:
  timezone: ${TIMEZONE:Asia/Dhaka}
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: 86400 # 24 hours in seconds
    refresh-expiration: 604800 # 7 days in seconds
  
  minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin123}
    bucket-name: attendance-faces
    
  face:
    embedding-dimension: ${EMBEDDING_DIM:512}
    similarity-threshold: ${SIMILARITY_THRESHOLD:0.6}
    quality-threshold: 0.7
    max-templates-per-employee: 10
    
  attendance:
    entry-window-start: "05:00"
    entry-window-end: "12:00"
    exit-window-start: "12:00"
    exit-window-end: "23:00"
    cooldown-minutes: 10
    late-threshold-minutes: 15
    early-leave-threshold-minutes: 15

---
spring:
  config:
    activate:
      on-profile: local
      
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_db
    
  jpa:
    show-sql: true
    
logging:
  level:
    com.company.attendance: DEBUG
    org.springframework.security: INFO

---
spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/attendance_db}
    
  jpa:
    show-sql: false
    
logging:
  level:
    com.company.attendance: INFO
    org.springframework.security: WARN
    root: INFO

app:
  minio:
    url: ${MINIO_URL:http://minio:9000}

---
spring:
  config:
    activate:
      on-profile: test
      
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    
  flyway:
    enabled: false

logging:
  level:
    com.company.attendance: DEBUG

# Application-specific configuration
app:
  edge-service:
    url: ${EDGE_SERVICE_URL:http://localhost:8081}
  security:
    jwt:
      secret: ${JWT_SECRET:my-super-secret-jwt-signing-key-change-in-production}
      expiration: ${JWT_EXPIRATION:86400} # 24 hours in seconds
